#Browser selection
browser=chrome
#APPLICATION URL
url=https://www.demoblaze.com
#APPLICATION USER NAME AND PASSWORD
username=test.vidyasara
password=test@123
title=Welcome test.vidyasara
name=Narmatha
country=india
city=chennai
creditCard=qerwge1324
month=march
year=2025
